/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react';
import api from '../api/axiosConfig';
import { createClassInvoices, getDebtReport, getFinanceReport, getInvoices, getPayments, recordPayment } from '../api/finance';
import AppShell from '../components/AppShell';
import Icon from '../components/Icon';

const currentPeriod = () => { const d = new Date(); return `${String(d.getMonth() + 1).padStart(2, '0')}-${d.getFullYear()}`; };
const money = (value) => new Intl.NumberFormat('vi-VN').format(value || 0) + ' đ';
const statusText = { unpaid: 'Chưa thu', partial: 'Thu một phần', paid: 'Đã thu đủ', cancelled: 'Đã hủy' };

export default function FinanceManagement() {
  const [tab, setTab] = useState('invoices'); const [classrooms, setClassrooms] = useState([]); const [invoices, setInvoices] = useState([]); const [debts, setDebts] = useState([]); const [report, setReport] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [payment, setPayment] = useState(null); const [payments, setPayments] = useState([]);
  const [filters, setFilters] = useState({ period: currentPeriod(), classroomId: '', status: '', search: '' });
  const [form, setForm] = useState({ classroomId: '', period: currentPeriod(), tuitionBase: '', mealFee: '0', busFee: '0', extraFee: '0', discount: '0', dueDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 5).toISOString().slice(0, 10), note: '' });
  const load = async () => { setLoading(true); setError(''); try { const [classRes, invoiceRes, debtRes, reportRes] = await Promise.all([api.get('/classrooms'), getInvoices(filters), getDebtReport({ period: filters.period, classroomId: filters.classroomId }), getFinanceReport(filters.period)]); setClassrooms(classRes.data.data || []); setInvoices(invoiceRes.data.data || []); setDebts(debtRes.data.data || []); setReport(reportRes.data.data); } catch (err) { setError(err.response?.data?.message || 'Không thể tải dữ liệu tài chính.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submitInvoices = async (event) => { event.preventDefault(); try { await createClassInvoices({ ...form, tuitionBase: Number(form.tuitionBase), mealFee: Number(form.mealFee), busFee: Number(form.busFee), extraFee: Number(form.extraFee), discount: Number(form.discount) }); setError(''); await load(); } catch (err) { setError(err.response?.data?.message || 'Không thể lập học phí.'); } };
  const openPayment = async (invoice) => { setPayment({ invoice, amount: Math.max(0, invoice.totalAmount - invoice.paidAmount), method: 'cash', note: '' }); try { const res = await getPayments(invoice._id); setPayments(res.data.data || []); } catch { setPayments([]); } };
  const submitPayment = async (event) => { event.preventDefault(); try { await recordPayment({ invoiceId: payment.invoice._id, amount: Number(payment.amount), method: payment.method, note: payment.note }); setPayment(null); await load(); } catch (err) { setError(err.response?.data?.message || 'Không thể ghi nhận thu tiền.'); } };
  return <AppShell title="Tài chính học phí" subtitle="Lập học phí theo lớp/tháng, thu tiền, công nợ, biên lai và báo cáo.">
    {error && <div className="form-error">{error}</div>}<section className="content-card timekeeping-hub"><div className="timekeeping-hub-tabs">{[{ key: 'invoices', label: 'Hóa đơn & Thu tiền' }, { key: 'create', label: 'Lập học phí theo lớp' }, { key: 'debts', label: 'Công nợ' }, { key: 'report', label: 'Báo cáo kỳ thu' }].map((item) => <button key={item.key} className={tab === item.key ? 'active' : ''} onClick={() => setTab(item.key)}>{item.label}</button>)}</div></section>
    {tab === 'invoices' && <section className="content-card student-list-card"><div className="list-toolbar"><div><p className="card-kicker">HÓA ĐƠN HỌC PHÍ</p><h2>Danh sách thu theo kỳ</h2></div><button className="button button-primary" onClick={load}><Icon name="search" size={16} />Làm mới</button></div><div className="student-filter-grid"><label>Kỳ thu<input value={filters.period} onChange={(e) => setFilters({ ...filters, period: e.target.value })} placeholder="09-2026" /></label><label>Lớp<select value={filters.classroomId} onChange={(e) => setFilters({ ...filters, classroomId: e.target.value })}><option value="">Tất cả lớp</option>{classrooms.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Trạng thái<select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Tất cả</option>{Object.entries(statusText).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Tìm học sinh<input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Tên học sinh" /></label></div><div className="form-actions"><button className="button button-secondary" onClick={load}>Áp dụng bộ lọc</button></div>{loading ? <div className="inline-loader"><span className="loading-orb" />Đang tải...</div> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Học sinh</th><th>Kỳ</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th><th>Trạng thái</th><th></th></tr></thead><tbody>{invoices.length ? invoices.map((item) => <tr key={item._id}><td>{item.studentName}<small>{item.className}</small></td><td>{item.period}</td><td>{money(item.totalAmount)}</td><td>{money(item.paidAmount)}</td><td>{money(item.totalAmount - item.paidAmount)}</td><td><span className={`student-status ${item.status === 'paid' ? 'enrolled' : item.status === 'partial' ? 'temporarily_absent' : 'withdrawn'}`}>{statusText[item.status]}</span></td><td>{item.status !== 'paid' && item.status !== 'cancelled' && <button className="button button-primary" onClick={() => openPayment(item)}>Thu tiền</button>}</td></tr>) : <tr><td colSpan="7">Chưa có hóa đơn phù hợp.</td></tr>}</tbody></table></div>}</section>}
    {tab === 'create' && <section className="content-card student-form"><div className="card-heading"><div><p className="card-kicker">LẬP HỌC PHÍ HÀNG LOẠT</p><h2>Tạo hóa đơn cho toàn bộ học sinh đang theo học</h2></div></div><form className="student-form-grid" onSubmit={submitInvoices}><label>Lớp học<select value={form.classroomId} onChange={(e) => setForm({ ...form, classroomId: e.target.value })} required><option value="">Chọn lớp</option>{classrooms.map((x) => <option key={x._id} value={x._id}>{x.name}</option>)}</select></label><label>Kỳ thu (MM-YYYY)<input value={form.period} onChange={(e) => setForm({ ...form, period: e.target.value })} required /></label><label>Học phí chính<input type="number" min="0" value={form.tuitionBase} onChange={(e) => setForm({ ...form, tuitionBase: e.target.value })} required /></label><label>Tiền ăn<input type="number" min="0" value={form.mealFee} onChange={(e) => setForm({ ...form, mealFee: e.target.value })} /></label><label>Tiền xe<input type="number" min="0" value={form.busFee} onChange={(e) => setForm({ ...form, busFee: e.target.value })} /></label><label>Khoản thu khác<input type="number" min="0" value={form.extraFee} onChange={(e) => setForm({ ...form, extraFee: e.target.value })} /></label><label>Giảm trừ<input type="number" min="0" value={form.discount} onChange={(e) => setForm({ ...form, discount: e.target.value })} /></label><label>Hạn thanh toán<input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} required /></label><label className="form-wide">Ghi chú<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} placeholder="Nội dung áp dụng chung cho kỳ thu này" /></label><div className="form-actions form-wide"><button className="button button-primary">Lập hóa đơn cho lớp</button></div></form></section>}
    {tab === 'debts' && <section className="content-card student-list-card"><div className="card-heading"><div><p className="card-kicker">CÔNG NỢ</p><h2>{money(debts.reduce((sum, item) => sum + item.remainingAmount, 0))} cần thu</h2></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Học sinh</th><th>Kỳ</th><th>Hạn thanh toán</th><th>Còn phải thu</th><th>Quá hạn</th></tr></thead><tbody>{debts.length ? debts.map((item) => <tr key={item._id}><td>{item.studentName}<small>{item.className}</small></td><td>{item.period}</td><td>{new Date(item.dueDate).toLocaleDateString('vi-VN')}</td><td>{money(item.remainingAmount)}</td><td>{item.overdue ? 'Quá hạn' : 'Trong hạn'}</td></tr>) : <tr><td colSpan="5">Không có công nợ.</td></tr>}</tbody></table></div></section>}
    {tab === 'report' && <section className="parent-summary-grid">{[['Hóa đơn', report?.totalInvoices], ['Phải thu', money(report?.totalAmount)], ['Đã thu', money(report?.totalPaid)], ['Còn phải thu', money(report?.totalRemaining)]].map(([label, value]) => <article key={label}><div><small>{label}</small><strong>{value || 0}</strong></div></article>)}</section>}
    {payment && <div className="modal-backdrop"><form className="content-card student-form" onSubmit={submitPayment}><div className="card-heading"><div><p className="card-kicker">THU TIỀN</p><h2>{payment.invoice.studentName} · {payment.invoice.period}</h2></div><button type="button" className="button button-secondary" onClick={() => setPayment(null)}>Đóng</button></div><div className="student-form-grid"><label>Số tiền thu<input type="number" min="1" max={payment.invoice.totalAmount - payment.invoice.paidAmount} value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} required /></label><label>Phương thức<select value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })}><option value="cash">Tiền mặt</option><option value="bank_transfer">Chuyển khoản</option><option value="ewallet">Ví điện tử</option></select></label><label className="form-wide">Ghi chú<input value={payment.note} onChange={(e) => setPayment({ ...payment, note: e.target.value })} placeholder="Ví dụ: Phụ huynh nộp tại quầy" /></label></div><div className="form-actions"><button className="button button-primary">Xác nhận thu tiền</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Biên lai</th><th>Ngày thu</th><th>Số tiền</th></tr></thead><tbody>{payments.map((item) => <tr key={item._id}><td>{item.receiptNumber || `PT-LEGACY-${item._id.slice(-6)}`}</td><td>{new Date(item.paidAt).toLocaleDateString('vi-VN')}</td><td>{money(item.amount)}</td></tr>)}</tbody></table></div></form></div>}
  </AppShell>;
}
