import { useCallback, useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
import api from '../api/axiosConfig';

const statusText = { pending: 'Chờ xử lý', in_progress: 'Đang xử lý', responded: 'Đã phản hồi', closed: 'Đã đóng' };
export default function ParentFeedbackManagement() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState('pending'); const [responses, setResponses] = useState({}); const [state, setState] = useState({ loading: true, saving: '', error: '', success: '' });
  const load = useCallback(async () => { try { setState((old) => ({ ...old, loading: true, error: '' })); const res = await api.get('/parent-feedback', { params: filter ? { status: filter } : {} }); setItems(res.data.data || []); setState((old) => ({ ...old, loading: false })); } catch (error) { setState({ loading: false, saving: '', success: '', error: error.response?.data?.message || 'Không thể tải phản hồi phụ huynh.' }); } }, [filter]);
  useEffect(() => { load(); }, [load]);
  const respond = async (id, status) => { try { setState((old) => ({ ...old, saving: id, error: '', success: '' })); await api.patch(`/parent-feedback/${id}/respond`, { status, response: responses[id] || '' }); await load(); setState((old) => ({ ...old, saving: '', success: status === 'in_progress' ? 'Đã chuyển phản hồi sang đang xử lý.' : 'Đã gửi phản hồi cho phụ huynh.' })); } catch (error) { setState((old) => ({ ...old, saving: '', error: error.response?.data?.message || 'Không thể cập nhật phản hồi.', success: '' })); } };
  return <AppShell title="Phản hồi phụ huynh" subtitle="Tiếp nhận góp ý riêng và phản hồi trực tiếp cho phụ huynh.">{state.error && <div className="form-error">{state.error}</div>}{state.success && <div className="timekeeping-notice success">{state.success}</div>}<section className="content-card profile-request-page"><div className="card-heading"><div><p className="card-kicker">HỘP THƯ RIÊNG</p><h2>Góp ý từ phụ huynh</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="pending">Chờ xử lý</option><option value="in_progress">Đang xử lý</option><option value="responded">Đã phản hồi</option><option value="closed">Đã đóng</option><option value="">Tất cả</option></select></div>{state.loading ? <div className="inline-loader"><span className="loading-orb" />Đang tải phản hồi...</div> : items.length ? <div className="profile-request-list">{items.map((item) => <article key={item._id}><header><div><span className="student-avatar">{item.studentName?.charAt(0) || 'B'}</span><div><strong>{item.subject}</strong><small>{item.studentName} · {item.className} · {item.parentName}</small></div></div><span className={`student-status ${item.status === 'responded' || item.status === 'closed' ? 'enrolled' : 'temporarily_absent'}`}>{statusText[item.status]}</span></header><div className="parent-feedback-manager-body"><p><b>Nội dung phụ huynh:</b> {item.message}</p>{item.response && <p className="school-response"><b>Phản hồi nhà trường:</b> {item.response}</p>}</div>{!['responded', 'closed'].includes(item.status) && <footer><textarea value={responses[item._id] || ''} onChange={(event) => setResponses({ ...responses, [item._id]: event.target.value })} placeholder="Nhập phản hồi gửi phụ huynh..." maxLength="3000" /><div><button type="button" className="button button-secondary" disabled={state.saving === item._id} onClick={() => respond(item._id, 'in_progress')}>Đang xử lý</button><button type="button" className="button button-primary" disabled={state.saving === item._id} onClick={() => respond(item._id, 'responded')}>{state.saving === item._id ? 'Đang gửi...' : 'Gửi phản hồi'}</button></div></footer>}</article>)}</div> : <div className="empty-state compact">Không có phản hồi phù hợp.</div>}</section></AppShell>;
}
