/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '../api/axiosConfig';
import { createLeaveRequest, getLeaveRequests } from '../api/attendance';
import AppShell from '../components/AppShell';
import Icon from '../components/Icon';

const attendanceText = { present: 'Có mặt', absent: 'Vắng', late: 'Đi muộn', absent_permission: 'Có phép' };
const leaveText = { pending: 'Đang chờ duyệt', approved: 'Đã duyệt', rejected: 'Từ chối', cancelled: 'Đã hủy' };
const dateText = (value) => value ? new Date(value).toLocaleDateString('vi-VN') : '—';
const money = (value) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value || 0);
const dishes = (meal) => (meal || []).map((item) => item.dishName || item.name).filter(Boolean).join(', ');
const today = () => new Date().toISOString().slice(0, 10);

export default function ParentPortal() {
  const [students, setStudents] = useState([]); const [selectedId, setSelectedId] = useState('');
  const [data, setData] = useState({ attendance: [], invoices: [], menus: [], leaves: [] });
  const [state, setState] = useState({ loading: true, error: '' }); const [leaveSaving, setLeaveSaving] = useState(false); const [leaveNotice, setLeaveNotice] = useState('');
  const [leaveForm, setLeaveForm] = useState({ startDate: today(), endDate: today(), reason: '' });
  const selected = useMemo(() => students.find((item) => item._id === selectedId), [students, selectedId]);

  const loadChildren = useCallback(async () => { try { const res = await api.get('/students', { params: { status: 'all', limit: 100, sortBy: 'fullName' } }); const list = res.data.data || []; setStudents(list); setSelectedId((current) => current || list[0]?._id || ''); } catch (err) { setState({ loading: false, error: err.response?.data?.message || 'Không thể tải hồ sơ của con.' }); } }, []);
  const loadChildData = useCallback(async () => { if (!selected) return; setState((old) => ({ ...old, loading: true, error: '' })); try { const end = today(); const startDate = new Date(); startDate.setDate(startDate.getDate() - 30); const [attendanceRes, invoiceRes, menuRes, leaveRes] = await Promise.all([api.get(`/attendance/student/${selected._id}`, { params: { startDate: startDate.toISOString().slice(0, 10), endDate: end } }), api.get(`/finance/tuition/student/${selected._id}`), api.get('/nutrition/menus', { params: { classroomId: selected.classroomId } }), getLeaveRequests()]); const leaves = (leaveRes.data.data || []).filter((item) => String(item.studentId) === selected._id); setData({ attendance: attendanceRes.data.data || [], invoices: invoiceRes.data.data || [], menus: menuRes.data.data || [], leaves }); setState({ loading: false, error: '' }); } catch (err) { setState({ loading: false, error: err.response?.data?.message || 'Không thể tải dữ liệu của con.' }); } }, [selected]);
  useEffect(() => { loadChildren(); }, [loadChildren]); useEffect(() => { loadChildData(); }, [loadChildData]);
  const submitLeave = async (event) => { event.preventDefault(); if (!selected) return; setLeaveSaving(true); setLeaveNotice(''); try { await createLeaveRequest({ studentId: selected._id, ...leaveForm }); setLeaveNotice('Đã gửi đơn xin nghỉ. Nhà trường sẽ phản hồi sau khi duyệt.'); setLeaveForm({ startDate: today(), endDate: today(), reason: '' }); await loadChildData(); } catch (err) { setLeaveNotice(err.response?.data?.message || 'Không thể gửi đơn xin nghỉ.'); } finally { setLeaveSaving(false); } };
  const upcomingInvoices = data.invoices.filter((item) => (item.totalAmount || 0) > (item.paidAmount || 0)); const latestMenu = data.menus[0];
  return <AppShell title="Cổng thông tin phụ huynh" subtitle="Theo dõi thông tin, điểm danh, thực đơn, học phí và gửi đơn xin nghỉ cho con.">
    {state.error && <div className="form-error">{state.error}</div>}
    {students.length > 1 && <section className="parent-child-switcher">{students.map((student) => <button key={student._id} className={student._id === selectedId ? 'active' : ''} onClick={() => setSelectedId(student._id)}><span className="student-avatar">{student.fullName?.charAt(0) || 'B'}</span><span><strong>{student.fullName}</strong><small>{student.currentClassName || 'Chưa xếp lớp'}</small></span></button>)}</section>}
    {state.loading && !selected ? <div className="page-loader"><span className="loading-orb" />Đang tải thông tin...</div> : !selected ? <div className="empty-state"><span className="empty-icon"><Icon name="students" /></span><strong>Chưa có hồ sơ học sinh được liên kết</strong><p>Vui lòng liên hệ nhà trường để xác minh thông tin phụ huynh và học sinh.</p></div> : <>
      <section className="parent-child-hero"><span className="student-avatar large">{selected.fullName?.charAt(0) || 'B'}</span><div><p className="card-kicker">{selected.studentCode}</p><h2>{selected.fullName}</h2><p>{selected.currentClassName || 'Chưa xếp lớp'} · {selected.gender === 'female' ? 'Nữ' : 'Nam'} · Sinh ngày {dateText(selected.birthDate)}</p></div><div><span className="student-status enrolled">{selected.status === 'enrolled' ? 'Đang theo học' : selected.status}</span></div></section>
      <section className="parent-summary-grid"><article><span><Icon name="attendance" /></span><div><small>Điểm danh 30 ngày</small><strong>{data.attendance.filter((item) => item.status === 'present').length} ngày có mặt</strong></div></article><article><span><Icon name="money" /></span><div><small>Học phí cần theo dõi</small><strong>{money(upcomingInvoices.reduce((sum, item) => sum + Math.max(0, (item.totalAmount || 0) - (item.paidAmount || 0)), 0))}</strong></div></article><article><span><Icon name="utensils" /></span><div><small>Thực đơn</small><strong>{latestMenu ? `Tuần ${latestMenu.weekNumber}` : 'Chưa công bố'}</strong></div></article></section>
      <section className="parent-portal-grid"><article className="content-card"><div className="card-heading"><div><p className="card-kicker">ĐIỂM DANH</p><h2>30 ngày gần đây</h2></div></div>{state.loading ? <div className="inline-loader"><span className="loading-orb" />Đang tải...</div> : data.attendance.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Ngày</th><th>Trạng thái</th><th>Giờ đến</th></tr></thead><tbody>{data.attendance.slice(0, 8).map((item) => <tr key={item._id}><td>{dateText(item.attendDate)}</td><td><span className={`student-status ${item.status === 'present' ? 'enrolled' : 'temporarily_absent'}`}>{attendanceText[item.status] || item.status}</span></td><td>{item.checkInTime ? new Date(item.checkInTime).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) : '—'}</td></tr>)}</tbody></table></div> : <div className="empty-state compact">Chưa có bản ghi điểm danh.</div>}</article><article className="content-card"><div className="card-heading"><div><p className="card-kicker">HỌC PHÍ</p><h2>Hóa đơn của con</h2></div></div>{upcomingInvoices.length ? <div className="parent-invoice-list">{upcomingInvoices.slice(0, 5).map((item) => <article key={item._id}><div><strong>Tháng {item.period}</strong><small>Hạn thanh toán: {dateText(item.dueDate)}</small></div><span>{money(Math.max(0, (item.totalAmount || 0) - (item.paidAmount || 0)))}</span></article>)}</div> : <div className="empty-state compact">Chưa có hóa đơn cần theo dõi.</div>}</article></section>
      <section className="parent-portal-grid parent-leave-grid"><article className="content-card student-form"><div className="card-heading"><div><p className="card-kicker">XIN NGHỈ</p><h2>Gửi đơn cho {selected.fullName}</h2></div></div>{leaveNotice && <div className={`timekeeping-notice ${leaveNotice.startsWith('Đã ') ? 'success' : 'error'}`}>{leaveNotice}</div>}<form className="student-form-grid" onSubmit={submitLeave}><label>Từ ngày<input type="date" min={today()} value={leaveForm.startDate} onChange={(e) => setLeaveForm({ ...leaveForm, startDate: e.target.value })} required /></label><label>Đến ngày<input type="date" min={leaveForm.startDate || today()} value={leaveForm.endDate} onChange={(e) => setLeaveForm({ ...leaveForm, endDate: e.target.value })} required /></label><label className="form-wide">Lý do xin nghỉ<textarea value={leaveForm.reason} onChange={(e) => setLeaveForm({ ...leaveForm, reason: e.target.value })} placeholder="Ví dụ: Bé bị sốt, cần nghỉ để theo dõi sức khỏe." minLength="5" maxLength="1000" required /></label><div className="form-actions form-wide"><button className="button button-primary" disabled={leaveSaving}>{leaveSaving ? 'Đang gửi...' : 'Gửi đơn xin nghỉ'}</button></div></form></article><article className="content-card"><div className="card-heading"><div><p className="card-kicker">PHẢN HỒI NHÀ TRƯỜNG</p><h2>Lịch sử đơn xin nghỉ</h2></div></div>{data.leaves.length ? <div className="parent-invoice-list">{data.leaves.slice(0, 6).map((item) => <article key={item._id}><div><strong>{dateText(item.startDate)} – {dateText(item.endDate)}</strong><small>{item.reviewNote || item.reason}</small></div><span className={`student-status ${item.status === 'approved' ? 'enrolled' : item.status === 'pending' ? 'temporarily_absent' : 'withdrawn'}`}>{leaveText[item.status]}</span></article>)}</div> : <div className="empty-state compact">Chưa có đơn xin nghỉ nào.</div>}</article></section>
      <section className="content-card parent-menu-card"><div className="card-heading"><div><p className="card-kicker">THỰC ĐƠN BÁN TRÚ</p><h2>{latestMenu ? `Thực đơn lớp ${selected.currentClassName || ''}` : 'Chưa có thực đơn được công bố'}</h2></div>{latestMenu && <span className="history-count">Tuần {latestMenu.weekNumber}</span>}</div>{latestMenu ? <div className="parent-menu-days">{(latestMenu.days || []).slice(0, 5).map((day) => <article key={day.dayOfWeek}><strong>{dateText(day.date) || day.dayOfWeek}</strong><p><b>Sáng:</b> {dishes(day.breakfast) || '—'}</p><p><b>Trưa:</b> {dishes(day.lunch) || '—'}</p><p><b>Xế:</b> {dishes(day.afternoonSnack) || '—'}</p></article>)}</div> : <div className="empty-state compact">Nhà trường chưa công bố thực đơn cho lớp này.</div>}</section>
    </>}
  </AppShell>;
}
