import { useCallback, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import AppShell from '../components/AppShell';
import { changeStudentStatus, getStudent } from '../api/students';

const labels = { pending_admission: 'Chờ nhập học', enrolled: 'Đang theo học', temporarily_absent: 'Tạm nghỉ', withdrawn: 'Đã thôi học', transferred: 'Đã chuyển trường', graduated: 'Đã tốt nghiệp' };
export default function StudentDetail() {
  const { id } = useParams(); const [student, setStudent] = useState(null); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const role = JSON.parse(localStorage.getItem('user') || '{}').role; const manager = ['admin', 'principal'].includes(role);
  const load = useCallback(() => getStudent(id).then((r) => { setStudent(r.data.data); setStatus(r.data.data.status); }).catch((e) => setError(e.response?.data?.message || 'Không thể tải hồ sơ học sinh.')), [id]);
  useEffect(() => { load(); }, [load]); const saveStatus = async () => { try { await changeStudentStatus(id, { status, effectiveDate: new Date().toISOString() }); load(); } catch (e) { setError(e.response?.data?.message || 'Không thể đổi trạng thái.'); } };
  return <AppShell title="Hồ sơ học sinh" subtitle="Tổng quan hồ sơ và lịch sử trạng thái."><section className="content-card student-detail">{error && <div className="form-error">{error}</div>}{!student && !error && <div className="empty-state">Đang tải hồ sơ...</div>}{student && <><div className="student-profile-head"><div className="student-avatar large">{student.fullName.charAt(0)}</div><div><p className="card-kicker">{student.studentCode}</p><h2>{student.fullName}</h2><p>{student.currentClassName || 'Chưa xếp lớp'} · {labels[student.status]}</p></div><div className="student-head-actions"><Link className="button button-secondary" to="/students">Quay lại</Link>{['admin', 'principal', 'teacher'].includes(role) && <Link className="button button-primary" to={`/students/${id}/edit`}>Chỉnh sửa</Link>}</div></div><div className="student-detail-grid"><article><h3>Thông tin tổng quan</h3><dl><dt>Ngày sinh</dt><dd>{new Date(student.birthDate).toLocaleDateString('vi-VN')}</dd><dt>Giới tính</dt><dd>{student.gender === 'female' ? 'Nữ' : 'Nam'}</dd><dt>Ngày nhập học</dt><dd>{student.admissionDate ? new Date(student.admissionDate).toLocaleDateString('vi-VN') : '—'}</dd><dt>Năm học</dt><dd>{student.schoolYear || '—'}</dd><dt>Địa chỉ</dt><dd>{student.address || '—'}</dd></dl></article><article><h3>Ghi chú chuyên môn</h3><p><b>Dị ứng:</b> {student.allergies?.map((item) => item.allergen).join(', ') || 'Không có dữ liệu'}</p><p><b>Bệnh lý:</b> {student.disease?.name || 'Không có dữ liệu'}</p><p><b>Ghi chú:</b> {student.notes || '—'}</p></article>{manager && <article className="status-change"><h3>Thay đổi trạng thái</h3><select value={status} onChange={(e) => setStatus(e.target.value)}>{Object.entries(labels).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select><button className="button button-primary" disabled={status === student.status} onClick={saveStatus}>Lưu trạng thái</button></article>}</div></>}</section></AppShell>;
}
