import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';
import Icon from '../components/Icon';
import { listStudents } from '../api/students';
import api from '../api/axiosConfig';

const statusText = { pending_admission: 'Chờ nhập học', enrolled: 'Đang theo học', temporarily_absent: 'Tạm nghỉ', withdrawn: 'Đã thôi học', transferred: 'Đã chuyển trường', graduated: 'Đã tốt nghiệp' };
export default function StudentList() {
  const navigate = useNavigate(); const [items, setItems] = useState([]); const [classes, setClasses] = useState([]); const [filters, setFilters] = useState({ search: '', classroomId: '', status: 'all', schoolYear: '2026-2027', page: 1, limit: 10 }); const [pagination, setPagination] = useState({}); const [state, setState] = useState({ loading: true, error: '' }); const role = JSON.parse(localStorage.getItem('user') || '{}').role;
  const load = useCallback(async () => { setState({ loading: true, error: '' }); try { const response = await listStudents(filters); setItems(response.data.data || []); setPagination(response.data.pagination || {}); } catch (err) { setState({ loading: false, error: err.response?.data?.message || 'Không thể tải danh sách học sinh.' }); return; } setState({ loading: false, error: '' }); }, [filters]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]); useEffect(() => { api.get('/classrooms').then((r) => setClasses(r.data.data || [])).catch(() => {}); }, []);
  const change = (key, value) => setFilters((old) => ({ ...old, [key]: value, page: key === 'page' ? value : 1 })); const canWrite = ['admin', 'principal', 'teacher'].includes(role);
  return <AppShell title="Học sinh" subtitle="Tra cứu, quản lý hồ sơ và trạng thái học sinh theo đúng phạm vi quyền." actions={canWrite && <button className="button button-primary" onClick={() => navigate('/students/new')}><Icon name="plus" size={17} />Thêm học sinh</button>}><section className="content-card student-list-card"><div className="student-filter-grid"><label className="search-box"><Icon name="search" size={18} /><input value={filters.search} onChange={(e) => change('search', e.target.value)} placeholder="Tìm theo tên hoặc mã học sinh" /></label><select value={filters.classroomId} onChange={(e) => change('classroomId', e.target.value)}><option value="">Tất cả lớp</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><select value={filters.status} onChange={(e) => change('status', e.target.value)}><option value="all">Tất cả trạng thái</option>{Object.entries(statusText).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><input value={filters.schoolYear} onChange={(e) => change('schoolYear', e.target.value)} placeholder="Năm học" /></div>{state.loading ? <div className="empty-state">Đang tải danh sách học sinh...</div> : state.error ? <div className="empty-state error"><strong>{state.error}</strong><button className="button button-secondary" onClick={load}>Thử lại</button></div> : !items.length ? <div className="empty-state"><strong>Chưa có học sinh phù hợp</strong><span>Thử thay đổi bộ lọc hoặc thêm hồ sơ mới.</span></div> : <><div className="student-table-wrap"><table className="data-table"><thead><tr><th>Mã học sinh</th><th>Học sinh</th><th>Lớp</th><th>Ngày sinh</th><th>Trạng thái</th><th /></tr></thead><tbody>{items.map((student) => <tr key={student._id}><td>{student.studentCode}</td><td><strong>{student.fullName}</strong><small>{student.gender === 'female' ? 'Nữ' : 'Nam'}</small></td><td>{student.currentClassName || '—'}</td><td>{student.birthDate ? new Date(student.birthDate).toLocaleDateString('vi-VN') : '—'}</td><td><span className={`student-status ${student.status}`}>{statusText[student.status] || student.status}</span></td><td><Link className="button button-secondary" to={`/students/${student._id}`}>Xem</Link></td></tr>)}</tbody></table></div><div className="student-pagination"><span>Hiển thị {items.length} / {pagination.total || 0} học sinh</span><div><button className="button button-secondary" disabled={filters.page <= 1} onClick={() => change('page', filters.page - 1)}>Trước</button><b>Trang {pagination.page || 1} / {pagination.totalPages || 1}</b><button className="button button-secondary" disabled={filters.page >= (pagination.totalPages || 1)} onClick={() => change('page', filters.page + 1)}>Sau</button></div></div></>}</section></AppShell>;
}
